---
title: "Odds Ratios"
author: ""
output:
  xaringan::moon_reader:
    css: "slides.css"
    lib_dir: libs
    nature:
      highlightLines: true
      highlightStyle: github
      countIncrementalSlides: false
---

```{r child = "setup.Rmd"}
```
layout: true

<div class="my-footer">
<span>
by Dr. Lucy D'Agostino McGowan
</span>
</div> 

---

# <i class="fas fa-laptop"></i> `Odds ratios`

- Go to RStudio Cloud and open `Odds ratios`
---

# Odds ratios

A study investigated whether a handheld device that sends a magnetic pulse into a person’s head
might be an effective treatment for migraine headaches.

* Researchers recruited 200 subjects who suffered from migraines 
* randomly assigned them to receive either the TMS (transcranial magnetic
stimulation) treatment or a placebo treatment 
* Subjects were instructed to apply the device at the onset of migraine symptoms and then assess how they felt two hours later. (either **Pain-free** or **Not pain-free**)

---

# Odds ratios

.question[
What is the explanatory variable?
]

A study investigated whether a handheld device that sends a magnetic pulse into a person’s head might be an effective treatment for migraine headaches.

* Researchers recruited 200 subjects who suffered from migraines 
* randomly assigned them to receive either the TMS (transcranial magnetic
stimulation) treatment or a placebo treatment 
* Subjects were instructed to apply the device at the onset of migraine symptoms and then assess how they felt two hours later (either **Pain-free** or **Not pain-free**)
---

# Odds ratios

.question[
What type of variable is this?
]

A study investigated whether a handheld device that sends a magnetic pulse into a person’s head might be an effective treatment for migraine headaches.

* Researchers recruited 200 subjects who suffered from migraines 
* randomly assigned them to receive either the TMS (transcranial magnetic
stimulation) treatment or a placebo treatment 
* Subjects were instructed to apply the device at the onset of migraine symptoms and then assess how they felt two hours later (either **Pain-free** or **Not pain-free**)
---

# Odds ratios

.question[
What is the outcome variable?
]

A study investigated whether a handheld device that sends a magnetic pulse into a person’s head might be an effective treatment for migraine headaches.

* Researchers recruited 200 subjects who suffered from migraines 
* randomly assigned them to receive either the TMS (transcranial magnetic
stimulation) treatment or a placebo treatment 
* Subjects were instructed to apply the device at the onset of migraine symptoms and then assess how they felt two hours later (either **Pain-free** or **Not pain-free**)
---

# Odds ratios

.question[
What type of variable is this?
]

A study investigated whether a handheld device that sends a magnetic pulse into a person’s head might be an effective treatment for migraine headaches.

* Researchers recruited 200 subjects who suffered from migraines 
* randomly assigned them to receive either the TMS (transcranial magnetic
stimulation) treatment or a placebo treatment 
* Subjects were instructed to apply the device at the onset of migraine symptoms and then assess how they felt two hours later (either **Pain-free** or **Not pain-free**)
---

# Odds ratios

|TMS | Placebo| Total
---|---|----|---
Pain-free two hours later |39| 22 |61
Not pain-free two hours later |61 |78| 139
Total| 100| 100 |200

--

* We can compare the results using **odds**

--
* What are the odds of being pain-free for the placebo group?

--
  * $(22/100)/(78/100) = 22/78 = 0.282$

--
* What are the odds of being pain-free for the treatment group?

--
  * $39/61 = 0.639$

--
* Comparing the **odds** what can we conclude?

--
  * TMS increases the likelihood of success
---

# Odds ratios

|TMS | Placebo| Total
---|---|----|---
Pain-free two hours later |39| 22 |61
Not pain-free two hours later |61 |78| 139
Total| 100| 100 |200

* We can summarize this relationship with an **odds ratio**: the ratio of the two odds

--
 
$\Large OR = \frac{39/61}{22/78} = \frac{0.639}{0.282} = 2.27$

--

_"the odds of being pain free were 2.27 times higher with TMS than with the placebo"_

---

# Odds ratios

.question[
What if we wanted to calculate this in terms of _Not pain-free_ (with _pain-free_) as the referent?
]

|TMS | Placebo| Total
---|---|----|---
Pain-free two hours later |39| 22 |61
Not pain-free two hours later |61 |78| 139
Total| 100| 100 |200

--

$\Large OR = \frac{61/39}{78/22} = \frac{1.564}{3.545} = 0.441$

--

_the odds for still being in pain for the TMS group are 0.441 times the odds of being in pain for the placebo group_
 
---

# Odds ratios

.question[
What changed here?
]

|TMS | Placebo| Total
---|---|----|---
Pain-free two hours later |39| 22 |61
Not pain-free two hours later |61 |78| 139
Total| 100| 100 |200


$\Large OR = \frac{78/22}{61/39} = \frac{3.545}{1.564} = 2.27$


_the odds for still being in pain for the placebo group are 2.27 times the odds of being in pain for the TMS group_
 
---


# Odds ratios

* In general, it's more natural to interpret odds ratios > 1, you can flip the referrant to do so

|TMS | Placebo| Total
---|---|----|---
Pain-free two hours later |39| 22 |61
Not pain-free two hours later |61 |78| 139
Total| 100| 100 |200


$\Large OR = \frac{78/22}{61/39} = \frac{3.545}{1.564} = 2.27$


_the odds for still being in pain for the placebo group are 2.27 times the odds of being in pain for the TMS group_

---

# <i class="fas fa-laptop"></i> `Odds ratios`

- Go to RStudio Cloud and open `Odds ratios`
