---
title: "Homework 2"
output: 
  tufte::tufte_html:
    css: "../labs/lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

**Due: October 24 at noon**
**turn in the .html file on Sakai**

Create a project called `Homework 2` on Rstudio.cloud

The `Diamonds` data set can be used to examine the relationship between a diamond's characteristics and it's price. Using the `Diamonds` data set in the `Stat2Data` package, we want to assess following models:

(#1) `TotalPrice` = $\beta_0 + \beta_1$`Depth` + $\beta_2$`Depth`$^2 + \epsilon$

(#2) `TotalPrice` = $\beta_0 + \beta_1$`Carat` + $\beta_2$`Depth`$+ \epsilon$

(#3) `TotalPrice` = $\beta_0 + \beta_1$`Carat` + $\beta_2$`Depth` + $\beta_3$`Depth`$\times$`Carat`$+ \epsilon$

## Inference

1. Fit the three models. For each model (1, 2, and 3), interpret all $\hat\beta$ coefficients.  
2. Report the confidence intervals for each $\hat\beta$

## Prediction

Following the steps outlined when we discussed how to conduct a [data analysis](https://sta-212-f19.lucymcgowan.com/reading/reading-data-analysis.html), create a report discussing the three models above. Use $R^2$ and adjusted $R^2$ to select your final prediction model. _Be sure to follow all of the steps outlined, including testing the assumptions of each model and including the proper plots to demonstrate that the assumptions have been met._


---

For this analysis, rank each of the following principles from the [Elements and Principles of Data Analysis](https://arxiv.org/pdf/1903.07639.pdf) article for this data analysis from 1 to 10 along with a one sentence summary:

- **data matching**: 
- **exhaustive**: 
- **skeptical**:
- **second order**:
- **transparency**:
- **reproducible**: