---
title: "Data Analysis"
output: html_document
---

## Abstract

* A short paragraph summary of the introduction, methods, results, and conclusions.

## Introduction

* The introduction should introduce your general research question and your data

## Methods

###  Describe your data. 

* How many observations are there?
* What are the observations? 
* What are the variables?
* Is there any missing data?

### Describe your methods.

* (If missing data exists) How are you going to deal with missing data?
* What models are you going to fit? 
* How are you going to evaluate whether the models meet their assumptions? 
* **If doing inference**: What hypothesis tests are you going?
* **If doing prediction**: How will you determine which model is best?

## Results

* Which model did you decide on?
* Demonstrate that this model fit the assumptions
* **If doing inference**
  * What are the $\beta$ coefficients of that model? What are their confidence intervals?
  * How do you interpret these $\beta$ coefficients in the context of this model?
  * What is the result of your hypothesis test?
* **If doing prediction**
  * What were the results of your "best" prediction model?
  * What is the equation for your prediction model?

## Discussion & Conclusion

* Summarize what you've learned and why it matters


## Appendix

* Include any code
* Include any additional plots / results that were used 
